version: "3"
services:
  gateway:
    volumes:
      - ./gateway/sites-available/cryptpad-master:/etc/nginx/sites-enabled/cryptpad
      - ./gateway/sites-available/nextcloud-master:/etc/nginx/sites-enabled/nextcloud
      - ./gateway/sites-available/nest-master:/etc/nginx/sites-enabled/nest
      - ./gateway/sites-available/community-master:/etc/nginx/sites-enabled/community
      - ./gateway/sites-available/webmail-master:/etc/nginx/sites-enabled/webmail

  cryptpad:
    container_name: cryptpad
    image: cryptpad/cryptpad
    restart: always
    depends_on:
      - gateway
    expose:
      - "3000"
      - "3001"
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./data/cryptpad/files:/cryptpad/datastore:rw
      - ./data/cryptpad/customize:/cryptpad/customize:rw
      - ./data/cryptpad/pins:/cryptpad/pins:rw
      - ./data/cryptpad/blob:/cryptpad/blob:rw
      - ./data/cryptpad/blobstage:/cryptpad/blobstage:rw
      - ./data/cryptpad/tasks:/cryptpad/tasks:rw
      - ./data/cryptpad/block:/cryptpad/block:rw
      - ./data/cryptpad/config:/cryptpad/cfg:rw
      - ./data/cryptpad/data:/cryptpad/data:rw
    networks:
      main:
        ipv4_address: 172.18.10.5

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: always
    expose:
      - "80"
      - "443"
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./data/nextcloud/:/var/www/html/
    environment:
      VIRTUAL_HOST: "cloud.parrot.sh"
      POSTGRES_DB: ${NEXTCLOUD_DB}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASS}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_PASS}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_USER}
    depends_on:
      - gateway
      - nextcloud-db
    networks:
      main:
        ipv4_address: 172.18.10.9
      nextcloud-db:

  nextcloud-db:
    container_name: nextcloud-db
    image: postgres
    restart: always
    volumes:
      - ./data/nextcloud-db/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${NEXTCLOUD_DB}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASS}
    networks:
      - nextcloud-db


networks:
  nextcloud-db:
    driver: bridge