version: "3"
services:
  gateway:
    volumes:
      - ./gateway/sites-available/cryptpad-master:/etc/nginx/sites-enabled/cryptpad
      - ./gateway/sites-available/nextcloud-master:/etc/nginx/sites-enabled/nextcloud
      - ./gateway/sites-available/nest-master:/etc/nginx/sites-enabled/nest
      - ./gateway/sites-available/community-master:/etc/nginx/sites-enabled/community
      - ./gateway/sites-available/webmail-master:/etc/nginx/sites-enabled/webmail

  nest:
    container_name: nest
    image: gitlab/gitlab-ce:latest
    restart: always
    expose:
      - "22"
      - "80"
      - "443"
      - "8090"
    ports:
      - "22:22"
      - "20080:80"
      - "20443:443"
      - "20081:8090"
    depends_on:
      - gateway
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://nest.parrotsec.org';
        gitlab_rails['lfs_enabled'] = true;
        gitlab_rails['gitlab_ssh_host'] = 'git.parrotsec.org'
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'nest@parrotsec.org'
        gitlab_rails['gitlab_email_display_name'] = 'Parrot Dev Portal'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@parrotsec.org'
        gitlab_rails['gitlab_email_subject_suffix'] = '[NEST]'
        gitlab_rails['gitlab_default_can_create_group'] = false
        gitlab_rails['gitlab_default_theme'] = 2
        gitlab_rails['incoming_email_enabled'] = true
        gitlab_rails['incoming_email_address'] = "nest+%{key}@parrotsec.org"
        gitlab_rails['incoming_email_email'] = "nest@parrotsec.org"
        gitlab_rails['incoming_email_host'] = "mail.parrotsec.org"
        gitlab_rails['incoming_email_port'] = 993
        gitlab_rails['incoming_email_ssl'] = true
        gitlab_rails['incoming_email_start_tls'] = false
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "mail.parrotsec.org"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = 'nest@parrotsec.org'
        gitlab_rails['smtp_domain'] = "mail.parrotsec.org"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        unicorn['worker_processes'] = 3
        letsencrypt['enable'] = false
        nginx['ssl_certificate'] = "/etc/ssl/private/fullchain.pem"
        nginx['ssl_certificate_key'] = "/etc/ssl/private/privkey.pem"
        pages_external_url "https://pages.nest.parrot.sh/"
        gitlab_pages['enable'] = true
        gitlab_pages['max_connections'] = 1000
        gitlab_pages['log_verbose'] = false
        gitlab_pages['listen_proxy'] = "0.0.0.0:8090"
        gitlab_pages['use_http2'] = true
        gitlab_pages['inplace_chroot'] = true
    volumes:
      - /root/certs:/etc/ssl/private
      - ./data/nest/config:/etc/gitlab:Z
      - ./data/logs/nest:/var/log/gitlab:Z
      - ./data/nest/data:/var/opt/gitlab:Z
    networks:
      main:
        ipv4_address: 172.18.10.6